### PR TITLE
setup project configuration

### PR DESCRIPTION
**Pull request by pacc0**
setup project configuration, cypress installation and first test from ramp up

### CODE REVIEW

**Review by holgiosalos — CHANGES_REQUESTED** [review]
Please make sure you have protected the `main` branch according to the following image:
image

**Comment by pacc0** [comment]
Protection Rule was already in place for the main branc
Screen Shot 2022-05-12 at 8 09 25 AM
h

**Comment by pacc0** [comment]
Also, it seems nobody else has accepted the invite to collab on the repository, so it's failing the 'CODEOWNERS' file in the .github folder

**Comment by holgiosalos** [comment]
> Protection Rule was already in place for the main branc Screen Shot 2022-05-12 at 8 09 25 AM h

It is weird because if you have that protection rule it should not leave you to merge or commit directly to the main branch before having an approved PR, and right now it is allowing to merge this PR without approval:
image

**Review by holgiosalos — APPROVED** [review]

**Pull request merged**
